// Markdown generated by scripts/sync-drive.ts from Google Docs in Hemsida.
import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'astro/zod';

const startsida = defineCollection({
  loader: glob({ base: './src/content/startsida', pattern: '*.md' }),
});

const braAttVeta = defineCollection({
  loader: glob({ base: './src/content/bra-att-veta', pattern: '*.md' }),
  schema: z.object({
    title: z.string(),
    summary: z.string(),
    modifiedTime: z.string(),
  }),
});

export const collections = { startsida, 'bra-att-veta': braAttVeta };
